services:
  bibleapi:
    build:
      context: ../
      dockerfile: ./docker/node/Dockerfile
    image: registry.docker.upcbq.com:443/bibleapi:${TAG:-latest}
    container_name: bibleapi
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      - APP
      - PORT
      - EXTERNAL_URL
      - HOSTNAME
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
