version: '3'

services:
  bibleapi:
    build:
      context: ../
      dockerfile: ./docker/node/Dockerfile
    image: bibleapi
    container_name: bibleapi
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      - APP
      - PORT
      - EXTERNAL_URL
      - HOSTNAME
      - DB_DIALECT
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
